### ISSUE TITLE
User feedback system

### ISSUE THREAD

**Issue by robines** [Samfundet/Samfundet4#1000]
We should consider having a system for allowing users to easily give feedback on the page they're viewing. This may just be something we use in the first month or two after launch, but I imagine it may give us valuable feedback from users who otherwise would not bother contacting us. Something like a floating button in the bottom corner of the page with just a text box (and optionally name/email if they want to be contacted regarding their feedback).

**Comment by tiniuspre** [comment]
Tenker du kun tekst feedback eller skal vi også ha radio knapper hvor det er litt som en "spørreundersøkelse. Feks at det alltid er knapper hvor du rangerer designet av siden 1-5, hvor rask siden er 1-5 osv også tekst til slutt.
