### ISSUE TITLE
Samform all fields are required even if spesified not to be required

### ISSUE THREAD

**Issue by tiniuspre** [Samfundet/Samfundet4#1007]
Can't submitt SamfForm when a field is blank even when it is not required

**Comment by aTrueYety** [comment]
Dette er egt ikke en bug, det er bare default i samfform at alle felt er required. Jeg vet ikke om dette er noe vi burde endre, gjerne kom med input.

![image](https://github.com/Samfundet/Samfundet4/assets/142814286/194fa2bd-c0ee-4ada-8e66-fb53d7db5c03)
