### ISSUE TITLE
Feedback input fields can't be blank

### ISSUE THREAD

**Issue by robines** [Samfundet/Samfundet4#1024]
It's not possible to clear the user feedback form input fields. To reproduce, open the form and type a character into any of the input fields, then attempt to delete it, which you'll see is not possible.

**Comment by tiniuspre** [comment]
This is a SamForm issue. Every field on SamForm is like this.

**Comment by tiniuspre** [comment]
This is a SamForm issue. Every field on SamForm is like this.
