### ISSUE TITLE
Fix SamfForm

### ISSUE THREAD

**Issue by aTrueYety** [Samfundet/Samfundet4#1025]
There are multiple issues with SamfForm currently and a rework would probably save a lot of time in further development.

**Comment by tiniuspre** [comment]
- Required set to false is still required
- When deleting characters the first can't be removed

**Comment by amaliejvik** [comment]
- Would like to be able to style the label on the field type checkbox

**Comment by tiniuspre** [comment]
- Group items
###### Example 
CheckBoxGroup where checkboxes automaticly align horizontaly
