### ISSUE TITLE
SamfForm field type multi select

### ISSUE THREAD

**Issue by tiniuspre** [Samfundet/Samfundet4#1032]
A multiselect would be nice for SamfForm .

LIke a group of checkboxes that return a list or grouped data.

**Comment by Mathias-a** [comment]
se https://github.com/Samfundet/Samfundet4/pull/854/files#diff-9b5e1b745180d58d04501d82dac3fffa44cd94b73ab2074059bafedbe25ff025

**Comment by Snorre98** [comment]
We have this/is being worked on: #1053
