### ISSUE TITLE
Breadcrumbs: Fetch recruitment, gang, and position information in router loader

### ISSUE THREAD

**Issue by robines** [Samfundet/Samfundet4#1087]
See https://github.com/Samfundet/Samfundet4/pull/996#issuecomment-2089416617

#996 must be merged first.

In order for the breadcrumbs to display the name of the recruitment/gang/position, we can preload the required information in the router loader. In the pages, we can then use [useLoaderData](https://reactrouter.com/en/main/hooks/use-loader-data#useloaderdata) or [useRouteLoaderData](https://reactrouter.com/en/main/hooks/use-route-loader-data) to get the data (to avoid loading the data twice)

**Comment by Snorre98** [comment]
@robines ferdig?
