### ISSUE TITLE
Implement permission system algorithm

### ISSUE THREAD

**Issue by emsoraffa** [Samfundet/Samfundet4#1125]
Implement the algorithm used to compute the cumulative permissions. See pdf for details. 
[Permissions 437cf529c5674359bee3a42bf77b24c2.pdf](https://github.com/Samfundet/Samfundet4/files/15312480/Permissions.437cf529c5674359bee3a42bf77b24c2.pdf)

**Comment by Snorre98** [comment]
Solved by  #1257, leverages Django functionality to get a permission structure we want.
