### ISSUE TITLE
Interviewers set applicant status 

### ISSUE THREAD

**Issue by Snorre98** [Samfundet/Samfundet4#1136]
Interviewers prioritizing applicants after interview. This is the "want", "reserve", "do not want" prioritization set by interviewers/admins during discussion at the end of the interview period.

Some of this has been started, so find out what has to be done before creating an issue from the tasks bellow. (hover over tasks to 'create issue' to the right)
- [x] #1157
- [x] #1158
- [ ] update applicant priority for other users
- [ ] implement backend api features in frontend

**Comment by magsyg** [comment]
Siste to blir allerede gjort i #987
