### ISSUE TITLE
Add endpoint for fetching recruitmentpositions for recruitment and gang

### ISSUE THREAD

**Issue by magsyg** [Samfundet/Samfundet4#1162]

**Comment by Snorre98** [comment]
@magsyg Vi har endepunkt for å hente posisjoner for gjeng: https://github.com/Samfundet/Samfundet4/blob/8aa907894a3b3d0106f3537e510a213ca63902fd/frontend/src/api.ts#L633C23-L633C54.

99% sikker på at vi har for recruitment også, men jeg skjønner ikke helt hva du tenker når du skriver "recruitmentpositions for recruitment".

Pleas sjekk om det er mer vi har som du har laget issues på. Ordet "admission" brukes ofte for "position", som er ganske forvirrende.

**Comment by Snorre98** [comment]
We have this now at least:  /recruitment-positions-gang-for-applicant/

http://localhost:8000/schema/redoc/#tag/recruitment-positions-gang-for-applicant

**Comment by Snorre98** [comment]
http://localhost:8000/schema/redoc/#tag/recruitment-positions/operation/recruitment_positions_list

http://localhost:8000/schema/redoc/#tag/recruitment-positions-gang-for-applicant
