### ISSUE TITLE
Add page for applicants without interview for gang

### ISSUE THREAD

**Issue by magsyg** [Samfundet/Samfundet4#1163]
Own page for to view applicants without interview but in gang scope

**Comment by Snorre98** [comment]
Overlapper en del med

https://github.com/Samfundet/Samfundet4/issues/1099

    https://github.com/Samfundet/Samfundet4/issues/1098

Kan være en tanke å samle disse på en side, med mulighet for å filtrer.

**Comment by Snorre98** [comment]
same as [#1224](https://github.com/Samfundet/Samfundet4/issues/1224)
