### ISSUE TITLE
Add page for show all applicants

### ISSUE THREAD

**Issue by magsyg** [Samfundet/Samfundet4#1164]
Needs a page for both a per gang, and all applicants for recruitment level

- [ ] Show all applicants for recruitment
- [ ] Show all applicants for gang

**Comment by Snorre98** [comment]
Overlapper en del med 
- https://github.com/Samfundet/Samfundet4/issues/1099
- https://github.com/Samfundet/Samfundet4/issues/1098

Kan være en tanke å samle disse på en side, med mulighet for å filtrer.

**Comment by Snorre98** [comment]
Usikker på om vi trenger side for å se alle søknader for et opptak, men #1099 og #1098 er noe som eksistere på Samf3.
