### ISSUE TITLE
Add form for separate positions

### ISSUE THREAD

**Issue by magsyg** [Samfundet/Samfundet4#1205]
Should not be a part of RecruitmentForm, but rather should be in its own simple form which can be similiar to how the occupied time form is handled, just have 3 fields of name_en, name_nb and url, and then be able to add and remove

**Comment by Frenje123** [comment]
So the issue here is that we use the RecruitmentForm to display "Gjenger med separate opptak" as well?

**Comment by Snorre98** [comment]
Solved by #1356
