### ISSUE TITLE
Set max applicantions per user in edit mode

### ISSUE THREAD

**Issue by Snorre98** [Samfundet/Samfundet4#1416]
"Max applications per user" is not being set in the "edit mode" form for recruitments.
[RecruitmentFormAdminPage](https://github.com/Samfundet/Samfundet4/blob/master/frontend/src/PagesAdmin/RecruitmentFormAdminPage/RecruitmentFormAdminPage.tsx)
There are other bugs in the form. Dont solve them, there is probably another isse for this.
http://localhost:3000/control-panel/recruitment/edit/1
[RecruitmentFormAdminPage](https://github.com/Samfundet/Samfundet4/blob/master/frontend/src/PagesAdmin/RecruitmentFormAdminPage/RecruitmentFormAdminPage.tsx)

**Comment by Mathias-a** [comment]
Hehehehehe 😓 Probably fixed by https://github.com/Samfundet/Samfundet4/pull/1502
