### ISSUE TITLE
Link unprocessed applet card to correct page

### ISSUE THREAD

**Issue by Snorre98** [Samfundet/Samfundet4#1446]
This is the correct page: http://localhost:3000/control-panel/recruitment/1/users-without-applications/
This is the code for the page: https://github.com/Samfundet/Samfundet4/blob/master/frontend/src/PagesAdmin/RecruitmentUnprocessedApplicantsPage/RecruitmentUnprocessedApplicantsPage.tsx

**Comment by nemisis84** [comment]
Solved in https://github.com/Samfundet/Samfundet4/pull/1512
