### ISSUE TITLE
Fix title next to favicon on multiple pages

### ISSUE THREAD

**Issue by Snorre98** [Samfundet/Samfundet4#1450]
The title next to the favicon

**Comment by andsamfu** [comment]
[Url to one of the pages that is affected](http://localhost:3000/control-panel/recruitment/1/separateposition/create)
Title on that site "Ukjent - Samfundet"

**Comment by andsamfu** [comment]
Found more pages with undefined title and created a list here with links.

Under "recruitment - gang overview" - showing "unknown":
- [ ] [RecruitmentSeparatePositioFormAdminPage](http://localhost:3000/control-panel/recruitment/1/separateposition/create)
- [ ] [RecruitmentRecruiterDashboardPage](http://localhost:3000/control-panel/recruitment/1/recruiter/dashboard/)
- [ ] [RecruitmentOverviewPage](http://localhost:3000/control-panel/recruitment/1/recruitment-overview/)
- [ ] [RoomAdminPage](http://localhost:3000/control-panel/recruitment/1/room-overview/)
- [ ] [RecruitmentUsersWithoutInterviewGangPage](http://localhost:3000/control-panel/recruitment/1/users-without-applications/)
- [ ] [RecruitmentUsersWithoutThreeInterviewCriteriaPage](http://localhost:3000/control-panel/recruitment/1/users-without-three-interviews/)

Under "roles" - showing previous title:
- [ ] [RolesAdminPage](http://localhost:3000/control-panel/roles/)
- [ ] [RoleAdminPage](http://localhost:3000/control-panel/roles/1)

Under "Lyche Menu" - showing previous title (use dynamic title?):
- [ ] [SultenMenuItemFormAdminPage](http://localhost:3000/control-panel/lyche/menuitems/create)
- [ ] Editmode for the page above with [edit link](http://localhost:3000/control-panel/lyche/menuitems/edit/1)

Under "recruitment - show" - showing previous title (use dynamic title?) :
- [ ] [OrganizationRecruitmentPage](http://localhost:3000/recruitment/1/)

**Comment by andsamfu** [comment]
More pages found:
- [x] [InterviewNotesAdminPage.](http://localhost:3000/control-panel/recruitment/1/gang/1/position/1/interview-notes/1)
- [ ] [RecruitmentApplicantAdminPage](http://localhost:3000/control-panel/recruitment/view-applicant/:applicationID/) someone else working on other PR. Skip for now
- [x] [RecruitmentGangAllApplicantsAdminPage](http://localhost:3000/control-panel/recruitment/1/1/all-applications/)
- [x] [RecruitmentPositionFormAdminPage](http://localhost:3000/control-panel/recruitment/1/gang/1/create/)
- [x] [UsersAdminPage](http://localhost:3000/control-panel/users/)
