### ISSUE TITLE
Interview notes on RecruitmentPositionOverviewPage

### ISSUE THREAD

**Issue by Snorre98** [Samfundet/Samfundet4#1470]
This has been worked on but is not finnished, There is some backend for this.

[This page](http://localhost:3000/control-panel/recruitment/1/gang/10/position/6)

Code for: [RecruitmentPositionOverviewPage](https://github.com/Samfundet/Samfundet4/blob/master/frontend/src/PagesAdmin/RecruitmentPositionOverviewPage/RecruitmentPositionOverviewPage.tsx)

**Comment by nemisis84** [comment]
After some discussion:

- The interview notes will be added on the recruitment user page: http://localhost:3000/control-panel/recruitment/view-applicant/912514b0-d16a-46f7-b1f9-a4930410046a/
- We will remove the notes field http://localhost:3000/control-panel/recruitment/2/gang/4/position/24

The notes field http://localhost:3000/control-panel/recruitment/2/gang/4/position/24 could be added later, but as a dropdown to choose priority
