### ISSUE TITLE
Checkbox disabled styling

### ISSUE THREAD

**Issue by emilte** [Samfundet/Samfundet4#265]

**Comment by emilte** [comment]
Status?

**Comment by Snorre98** [comment]
Planen var å bli ferdig med den på søndag(i dag).

Sendt fra Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: Emil Telstad ***@***.***>
Sendt: Sunday, April 9, 2023 12:28:45 AM
Til: Samfundet/Samfundet4 ***@***.***>
Kopi: Snorre98 ***@***.***>; Assign ***@***.***>
Emne: Re: [Samfundet/Samfundet4] Checkbox disabled styling (Issue #265)


Status?
