### ISSUE TITLE
Add more common translations

### ISSUE THREAD

**Issue by magsyg** [Samfundet/Samfundet4#288]
Looks like a lot of translations could be split up such as:
Create group, could be 'common_create',  and 'group'.
Translations that are just a combination of two simple reusable words should be split up

Should maybe also be smart to create subfolders for common, and page translations later

**Comment by emilte** [comment]
Man kan lage translations når man trenger det. Det er enklest å ikke kombinere, for refaktorering kan bli vanskelig.
