### ISSUE TITLE
Complete Event form

### ISSUE THREAD

**Issue by magsyg** [Samfundet/Samfundet4#314]
Add image select
Add datetime select
Add Price

**Comment by evgiz** [comment]
Image select & datetime select er ferdig #436 
Vi trenger en egen komponent for valg av pris, men denne burde nok vente til vi har funnet ut hvordan alle betaling/påmeldingstypene skal fungere.

**Comment by evgiz** [comment]
Lukker denne og lager nytt issue på payment.
