### ISSUE TITLE
Make forms more understandable

### ISSUE THREAD

**Issue by magsyg** [Samfundet/Samfundet4#339]
When I have created these forms I have mostly only cared about functionality, but they should also be more understandable to use
So I need the admin forms to have:
- More descriptive labels
- Explanatory text
- Make confirm button look nicer

And such things

**Comment by evgiz** [comment]
Kan godt ta ansvar for å gjøre forms penere, de trenger definitivt en liten makeover. Mtp. explanatory text kan jeg se på å legge opp til det i hvertfall, men er mye greier som må ordnes mtp gode errors osv. Assigner denne til meg inntil videre men lurer på om det blir fornuftig å dele det opp i flere issues.

**Comment by evgiz** [comment]
Mye av dette er løst i #436 som støtter bl.a. custom validation errors.
Man kan også legge inn sine egne forklaringer hvis det er absolutt nødvendig. Kanskje lukke denne @magsyg ?

**Comment by emilte** [comment]
Jeg tror ikke Magnus får mails Sigve
