### ISSUE TITLE
Opprett arrangement oppsummering disabled

### ISSUE THREAD

**Issue by emilte** [Samfundet/Samfundet4#511]
Datepicker på oppsummering bør være disabled.

**Comment by evgiz** [comment]
Hvorfor det?

**Comment by emilte** [comment]
Den har ingen effekt.

**Comment by evgiz** [comment]
Joda, man må legge inn publiseringsdato før man lagrer, og det blir lagt inn i publish_dt i databasen. Dobbeltsjekket nettopp.

**Comment by emilte** [comment]
Da har jeg gjort noe rart da jeg testet.
