### ISSUE TITLE
Move context providers from individual stories to decorators

### ISSUE THREAD

**Issue by evgiz** [Samfundet/Samfundet4#552]
Several stories use context providers
```tsx
<AuthContextProvider>
      <GlobalContextProvider>
         {/* Some story */}
      </GlobalContextProvider>
</AuthContextProvider>
```
I see no need to do this manually lots of different places, so it can be moved to a storybook decorator instead.

**Comment by emilte** [comment]
Jeg synes det er greit at det må skrives manuelt. Det viser tydelig hva som skal til for å bruke en komponent, hva den er avhengig av og ikke. Trenger ikke gi dem mer enn nødvendig?

**Comment by emilte** [comment]
Det er noe av poenget med Template
