### ISSUE TITLE
Create Listview component with integrated sorting

### ISSUE THREAD

**Issue by Frenje123** [Samfundet/Samfundet4#571]
We need a component that can sort based on column elements. 
This Listview on Samfundet3 would be nice to be able to sort:
![image](https://user-images.githubusercontent.com/48588529/232853611-d460e53a-e6f6-43d6-9e36-983bf4a787b8.png)

**Comment by evgiz** [comment]
Tabellkomponenten er allerede sorterbar, eller misforstår jeg hva du mener her?

**Comment by Frenje123** [comment]
> Tabellkomponenten er allerede sorterbar, eller misforstår jeg hva du mener her?

Yes, du har rett
