### ISSUE TITLE
Create view for viewing individual application

### ISSUE THREAD

**Issue by KevinKristiansen** [Samfundet/Samfundet4#670]
**Frontend Skeleton for such a view/page** (No fuctionality)

We should have a view for viewing individual applications. This view should include application text, positions the applicant has searched for, and other relevant information. 

[Here is the Samf3-solution.](https://www-beta.samfundet.no/opptak-administrasjon/opptak/89-test-opptak24/gjenger/988-mg/verv/1851-weebdeveloper/soknader/6688)

**Comment by magsyg** [comment]
Usikker på om denne er ferdig, har gjort meste her, men må sjekke
