### ISSUE TITLE
Logging in via frontend doesn't work

### ISSUE THREAD

**Issue by robines** [Samfundet/Samfundet4#714]
Logging in via frontend doesn't work anymore. Bug was introduced some time after cda9593439d17c8d601043ea5bec00ec2ab3ef0a.

A workaround is to log in via the Django admin panel, then refresh frontend.

**Comment by emilte** [comment]
Denne tror jeg Sigve har fikset

**Comment by aTrueYety** [comment]
@robines close?

**Comment by robines** [comment]
@aTrueYety si señor
