### ISSUE TITLE
Fix closed period submission

### ISSUE THREAD

**Issue by amaliejvik** [Samfundet/Samfundet4#977]
Make it possible to submit a closed period with form in the control panel.
Also fix the form design and text.

**Comment by amaliejvik** [comment]
Fix buttons:
<img width="599" alt="image" src="https://github.com/Samfundet/Samfundet4/assets/125203980/22cf3630-5e93-4444-bdfb-d55caa0126e3">

**Comment by aTrueYety** [comment]
Closes with #1031
