### ISSUE TITLE
Make SamfFormField's DateTime compatible with initial data

### ISSUE THREAD

**Issue by amaliejvik** [Samfundet/Samfundet4#983]
Currently, the DateTime-field type does not display initial data like the other field types do

**Comment by aTrueYety** [comment]
Example of a bug this causes:
*IMG 1*
![image](https://github.com/Samfundet/Samfundet4/assets/142814286/6e4032b4-74ac-4a31-a860-b34d22dadb0c)

*IMG 2*
![image](https://github.com/Samfundet/Samfundet4/assets/142814286/3b56ee7f-07b2-497c-93ae-eb0c7001fddf)

*IMG 1* shows the formatting of date objects like the backend stores them. *IMG 2* shows the expected formating and the subsequent default value of the datetime field type when the wrong formatting is provided.
